In [48]:
import numpy as np
def f(x):
    return np.e**x - x**2 - 4

def f_(x):
    return np.e**x - 2*x

x0 = 0
x_anterior = 0
count = 0
for i in range(6):
    xi = x_anterior - f(x_anterior)/f_(x_anterior)
    print('xi = %.6lf, x%d = %.6lf, f(%.6lf) = %.6lf' % (xi, count, x_anterior, xi, f(xi)))
    x_anterior = xi
    count+=1
    

xi = 3.000000, x0 = 0.000000, f(3.000000) = 7.085537
xi = 2.496964, x1 = 3.000000, f(2.496964) = 1.910732
xi = 2.229789, x2 = 2.496964, f(2.229789) = 0.325947
xi = 2.162422, x3 = 2.229789, f(2.162422) = 0.016094
xi = 2.158737, x4 = 2.162422, f(2.158737) = 0.000045
xi = 2.158726, x5 = 2.158737, f(2.158726) = 0.000000


In [45]:
import numpy as np

def vandermode_pol(x, y):
    X = np.vander(x, x.shape[0])
    print(X)
    return np.linalg.solve(X,y)

def newton(x, y):
    pxi = 0
    degree = x.shape[0]
    for i, coef in enumerate(x):
        pxi += coef * y ** (degree -1)
    return pxi


t = np.array([0,1,2,3,4])
f_t = np.array([0.03, 0.96, 0.13, -0.87, -0.04])
print(vandermode_pol(t, f_t))

[[  0   0   0   0   1]
 [  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[ 0.01708333  0.1625     -1.48708333  2.2375      0.03      ]


In [65]:
import numpy as np

def line(x,y):
    left = np.array([[np.sum(x*x), np.sum(x)], [np.sum(x), x.shape[0]]])
    print(left)
    right = np.array([np.sum(x*y), np.sum(y)])
    print(right)
    [a, b] = np.linalg.solve(left, right)
    return [a,b]

# def mmq(x, y):
    

t = np.array([0,1,2,3,4,5,6,7,8,9,10])
h_t = np.array([5.0,4.96,4.78,4.53,4.19,3.72,3.18,2.55,1.77,1.01,0.0])
print(t)
print(h_t)
result = line(t, h_t)
print(result)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 5.    4.96  4.78  4.53  4.19  3.72  3.18  2.55  1.77  1.01  0.  ]
[[385  55]
 [ 55  11]]
[ 123.65   35.69]
[-0.4981818181818185, 5.7354545454545471]
